overwrite DEF_KEYSIZE and DEF_DAYS over environment variables DEF_KEYSIZE increased to 4096
creating of SUBJECT simplified

use sha512 for creating a request
uniform use of spaces instead of tabs

diff --git a/bin/ca-gen b/bin/ca-gen
--- a/bin/ca-gen
+++ b/bin/ca-gen
@@ -7,8 +7,8 @@ set -o pipefail
 NAME="ca-gen"
 
 # Generate default options
-DEF_KEYSIZE=2048
-DEF_DAYS=3650
+DEF_KEYSIZE=${DEF_KEYSIZE:-4096}
+DEF_DAYS=${DEF_DAYS:-3650}
 # Subject default options
 DEF_COUNTRY=
 DEF_STATE=
@@ -23,30 +23,31 @@ DEF_VERBOSE=
 
 
 print_version() {
-	echo "${NAME} v0.2"
+  echo "${NAME} v0.2"
 }
+
 print_help() {
-	echo "USAGE: ${NAME} -n CN [-kdcslouev] <keyfile> <crtfile>"
-	echo "       ${NAME} --help"
-	echo "       ${NAME} --version"
-	echo
-	echo "Required arguments"
-	echo "  -n CN       Common Name"
-	echo
-	echo "Optional arguments"
-	echo "  -k int      Key size in bits"
-	echo "  -d int      Validity in days"
-	echo "  -c C        Subject two letter country name (C)"
-	echo "  -s ST       Subject state name (ST)"
-	echo "  -l L        Subject location (L)"
-	echo "  -o O        Subject organization (O)"
-	echo "  -u OU       Subject organizational unit (OU)"
-	echo "  -e Email    Subject email (emailAddress)"
-	echo "  -v          Verbose output"
-	echo
-	echo "Required parameter"
-	echo "  <keyfile>   Path to output key file"
-	echo "  <crtfile>   Path to output cert file"
+  echo "USAGE: ${NAME} -n CN [-kdcslouev] <keyfile> <crtfile>"
+  echo "       ${NAME} --help"
+  echo "       ${NAME} --version"
+  echo
+  echo "Required arguments"
+  echo "  -n CN       Common Name"
+  echo
+  echo "Optional arguments"
+  echo "  -k int      Key size in bits"
+  echo "  -d int      Validity in days"
+  echo "  -c C        Subject two letter country name (C)"
+  echo "  -s ST       Subject state name (ST)"
+  echo "  -l L        Subject location (L)"
+  echo "  -o O        Subject organization (O)"
+  echo "  -u OU       Subject organizational unit (OU)"
+  echo "  -e Email    Subject email (emailAddress)"
+  echo "  -v          Verbose output"
+  echo
+  echo "Required parameter"
+  echo "  <keyfile>   Path to output key file"
+  echo "  <crtfile>   Path to output cert file"
 }
 
 
@@ -56,79 +57,79 @@ print_help() {
 
 # Get options
 while [ ${#} -gt 0 ]; do
-	case "${1}" in
-		# ---- Help / version
-		--version)
-			print_version
-			exit
-			;;
-		--help)
-			print_help
-			exit
-			;;
-		-v)
-			DEF_VERBOSE=1
-			shift
-			;;
-		# ---- Options
-		-k)
-			shift
-			DEF_KEYSIZE="${1}"
-			shift
-			;;
-		-d)
-			shift
-			DEF_DAYS="${1}"
-			shift
-			;;
-		-c)
-			shift
-			DEF_COUNTRY="${1}"
-			shift
-			;;
-		-s)
-			shift
-			DEF_STATE="${1}"
-			shift
-			;;
-		-l)
-			shift
-			DEF_CITY="${1}"
-			shift
-			;;
-		-o)
-			shift
-			DEF_ORG="${1}"
-			shift
-			;;
-		-u)
-			shift
-			DEF_UNIT="${1}"
-			shift
-			;;
-		-n)
-			shift
-			DEF_CN="${1}"
-			shift
-			;;
-		-e)
-			shift
-			DEF_EMAIL="${1}"
-			shift
-			;;
-		# ---- Stop here
-		--) # End of all options
-			shift
-			break
-			;;
-		-*) # Unknown option
-			>&2 echo "Error: Unknown option: ${1}"
-			exit 1
-			;;
-		*)  # No more options
-			break
-			;;
-	esac
+  case "${1}" in
+    # ---- Help / version
+    --version)
+      print_version
+      exit
+      ;;
+    --help)
+      print_help
+      exit
+      ;;
+    -v)
+      DEF_VERBOSE=1
+      shift
+      ;;
+    # ---- Options
+    -k)
+      shift
+      DEF_KEYSIZE="${1}"
+      shift
+      ;;
+    -d)
+      shift
+      DEF_DAYS="${1}"
+      shift
+      ;;
+    -c)
+      shift
+      DEF_COUNTRY="${1}"
+      shift
+      ;;
+    -s)
+      shift
+      DEF_STATE="${1}"
+      shift
+      ;;
+    -l)
+      shift
+      DEF_CITY="${1}"
+      shift
+      ;;
+    -o)
+      shift
+      DEF_ORG="${1}"
+      shift
+      ;;
+    -u)
+      shift
+      DEF_UNIT="${1}"
+      shift
+      ;;
+    -n)
+      shift
+      DEF_CN="${1}"
+      shift
+      ;;
+    -e)
+      shift
+      DEF_EMAIL="${1}"
+      shift
+      ;;
+    # ---- Stop here
+    --) # End of all options
+      shift
+      break
+      ;;
+    -*) # Unknown option
+      >&2 echo "Error: Unknown option: ${1}"
+      exit 1
+      ;;
+    *)  # No more options
+      break
+      ;;
+  esac
 done
 
 
@@ -137,13 +138,13 @@ done
 ################################################################################
 
 if [ -z "${DEF_CN}" ]; then
-	>&2 echo "Error: -n is required. See --help for help."
-	exit 1
+  >&2 echo "Error: -n is required. See --help for help."
+  exit 1
 fi
 
 if [ "${#}" -lt "2" ]; then
-	>&2 echo "Error: <keyfile> and <crtfile> are required. See --help for help."
-	exit 1
+  >&2 echo "Error: <keyfile> and <crtfile> are required. See --help for help."
+  exit 1
 fi
 
 CA_KEY_FILE="${1}"
@@ -159,27 +160,13 @@ CA_CRT_FILE="${2}"
 ### Build subject
 ###
 SUBJECT=
-if [ -n "${DEF_COUNTRY}" ]; then
-	SUBJECT="${SUBJECT}/C=${DEF_COUNTRY}"
-fi
-if [ -n "${DEF_STATE}" ]; then
-	SUBJECT="${SUBJECT}/ST=${DEF_STATE}"
-fi
-if [ -n "${DEF_CITY}" ]; then
-	SUBJECT="${SUBJECT}/L=${DEF_CITY}"
-fi
-if [ -n "${DEF_ORG}" ]; then
-	SUBJECT="${SUBJECT}/O=${DEF_ORG}"
-fi
-if [ -n "${DEF_UNIT}" ]; then
-	SUBJECT="${SUBJECT}/OU=${DEF_UNIT}"
-fi
-if [ -n "${DEF_CN}" ]; then
-	SUBJECT="${SUBJECT}/CN=${DEF_CN}"
-fi
-if [ -n "${DEF_EMAIL}" ]; then
-	SUBJECT="${SUBJECT}/emailAddress=${DEF_EMAIL}"
-fi
+[ -n "${DEF_COUNTRY}" ] && SUBJECT="${SUBJECT}/C=${DEF_COUNTRY}"
+[ -n "${DEF_STATE}" ]   && SUBJECT="${SUBJECT}/ST=${DEF_STATE}"
+[ -n "${DEF_CITY}" ]    && SUBJECT="${SUBJECT}/L=${DEF_CITY}"
+[ -n "${DEF_ORG}" ]     && SUBJECT="${SUBJECT}/O=${DEF_ORG}"
+[ -n "${DEF_UNIT}" ]    && SUBJECT="${SUBJECT}/OU=${DEF_UNIT}"
+[ -n "${DEF_CN}" ]      && SUBJECT="${SUBJECT}/CN=${DEF_CN}"
+[ -n "${DEF_EMAIL}" ]   && SUBJECT="${SUBJECT}/emailAddress=${DEF_EMAIL}"
 
 
 ###
@@ -200,16 +187,16 @@ cmd="$( echo "${cmd}" | tr -s " " )"
 
 # Debug
 if [ "${DEF_VERBOSE}" = "1" ]; then
-	echo "\$ ${cmd}"
+  echo "\$ ${cmd}"
 fi
 
 # Execute
 if ! out="$( eval "${cmd}" 2>&1 )"; then
-	if [ -z "${DEF_VERBOSE}" ]; then
-		echo "\$ ${cmd}"
-	fi
-	>&2 echo "${out}"
-	exit 1
+  if [ -z "${DEF_VERBOSE}" ]; then
+    echo "\$ ${cmd}"
+  fi
+  >&2 echo "${out}"
+  exit 1
 fi
 
 
@@ -232,7 +219,7 @@ cmd="openssl req \
   -new \
   -x509 \
   -nodes \
-  -sha256 \
+  -sha512 \
   -days ${DEF_DAYS} \
   -key ${CA_KEY_FILE} \
   -subj '${SUBJECT}' \
@@ -244,16 +231,16 @@ cmd="$( echo "${cmd}" | tr -s " " )"
 
 # Debug
 if [ "${DEF_VERBOSE}" = "1" ]; then
-	echo "\$ ${cmd}"
+  echo "\$ ${cmd}"
 fi
 
 # Execute
 if ! out="$( eval "${cmd}" 2>&1 )"; then
-	if [ -z "${DEF_VERBOSE}" ]; then
-		echo "\$ ${cmd}"
-	fi
-	>&2 echo "${out}"
-	exit 1
+  if [ -z "${DEF_VERBOSE}" ]; then
+    echo "\$ ${cmd}"
+  fi
+  >&2 echo "${out}"
+  exit 1
 fi
 
 
@@ -261,17 +248,17 @@ fi
 ### 4. Validate
 ###
 if ! out="$( openssl x509 -in "${CA_CRT_FILE}" -text )"; then
-	echo "${out}"
-	exit 1
+  echo "${out}"
+  exit 1
 fi
 if [ "${DEF_VERBOSE}" = "1" ]; then
-	echo "${out}"
+  echo "${out}"
 fi
 
 if ! out="$( openssl x509 -noout -subject -issuer -in "${CA_CRT_FILE}" )"; then
-	echo "${out}"
-	exit 1
+  echo "${out}"
+  exit 1
 fi
 if [ "${DEF_VERBOSE}" = "1" ]; then
-	echo "${out}"
+  echo "${out}"
 fi
